2023/06/05 02:06:08 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.4:9000", host: "localhost:8080"
2023/06/07 13:54:53 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.48.4:9000", host: "localhost:8080"
2023/06/07 13:54:56 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.48.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.48.4:9000", host: "localhost:8080"
2023/06/08 14:59:34 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: _, request: "GET /users HTTP/1.1", upstream: "fastcgi://192.168.112.5:9000", host: "localhost:8080", referrer: "http://localhost:8080/users"
2023/06/08 14:59:35 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: _, request: "GET /users HTTP/1.1", upstream: "fastcgi://192.168.112.5:9000", host: "localhost:8080", referrer: "http://localhost:8080/users"
2023/06/08 14:59:39 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.112.5:9000", host: "localhost:8080", referrer: "http://localhost:8080/"
2023/06/08 14:59:49 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.112.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.112.5:9000", host: "localhost:8080"
2023/06/10 02:06:40 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.192.1, server: _, request: "GET /users HTTP/1.1", upstream: "fastcgi://192.168.192.5:9000", host: "localhost:8080"
2023/06/10 02:06:41 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.192.1, server: _, request: "GET /users HTTP/1.1", upstream: "fastcgi://192.168.192.5:9000", host: "localhost:8080"
2023/06/10 02:06:41 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.192.1, server: _, request: "GET /users HTTP/1.1", upstream: "fastcgi://192.168.192.5:9000", host: "localhost:8080"
2023/06/10 02:53:48 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: _, request: "GET /quizzes/create HTTP/1.1", upstream: "fastcgi://192.168.208.5:9000", host: "localhost:8080", referrer: "http://localhost:8080/quizzes"
2023/06/10 02:53:52 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: _, request: "GET /users HTTP/1.1", upstream: "fastcgi://192.168.208.5:9000", host: "localhost:8080"
2023/06/10 02:53:56 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.5:9000", host: "localhost:8080"
2023/06/10 02:54:09 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.208.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.208.5:9000", host: "localhost:8080"
